version: '3.7'
services:
  chemy:
    image: chemy
    build: .
    volumes:
      - socket:/shared
    environment:
      SOCKET_PATH: "/shared/chemy.sock"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped

  nginx:
    image: ksptool-static
    build: ksp-compare-tool
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - socket:/shared
    depends_on:
      - chemy

volumes:
  socket:
