version: '3.7'
services:
  chemy:
    image: chemy
    build: .
    volumes:
      - socket:/shared
    environment:
      SOCKET_PATH: "/shared/chemy.sock"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped

  nginx:
    image: ksptool-static
    ports:
      - 80:80
    volumes:
      - socket:/shared
    depends_on:
      - chemy

volumes:
  socket:
